### ISSUE TITLE
Empty Dictionaries fail

### ISSUE THREAD

**Issue by adam-rocska** [mat-sz/plist#1] opened 2024-01-07 15:41 UTC
If the file contains empty dictionaries (or empty stuff generally), like:
```
// !$*UTF8*$!
{
  archiveVersion = 1;
  classes = {};
```

The library fails with:
```
 throw new Error("Unexpected '".concat(char, "'"));
                ^

Error: Unexpected '}'
```

**Comment by mat-sz** [comment] 2024-01-09 17:59
@adam-rocska Your example is parsing just fine, could you provide an example that reproduces the problem?

**Comment by mat-sz** [comment] 2024-01-10 17:37
@adam-rocska Upon further analysis looks like this causes issues:

```
{
  classes = {
  };
}
```

Fixed in 1.1.0.

**Closed as completed by mat-sz** 2024-01-10 17:37 UTC
Labels: bug
